### PR TITLE
Separate validation from getting body

### PR DESCRIPTION
**Pull request by erritis**
I made it so that we first receive the payload, validate it separately
and only then convert it to the type we need. True, now the validation
needs to be registered separately, that is, it has ceased to be
mandatory

When writing your own middleware, there is no way to interact directly
with the payload, which prevents you from writing your own validator
for the payload
When you write your middleware to cast claims to a different type than
what will be used in the endpoint, the decoding and validation is
re-executed in that middleware

### CODE REVIEW

**Comment by olger** [comment]
Thanks for your PR, it seems that this contains the commits of the other PR, is that right ?

**Comment by erritis** [comment]
> Thanks for your PR, it seems that this contains the commits of the other PR, is that right ?

Yes.
In the first PR, I simply removed the need to add a biscuit to the project and removed the dependencies. In theory, those two commits also had to be sent separately, but both changes are very small and I did not break them. And in theory, they should not be in the second PR, but I didn’t want to accidentally remove something in it again and decided to continue from the previous PR.
In the second PR, also stall a change in the way of testing, first issue as a PR, but decided to send it already.

**Comment by olger** [comment]
Thanks for the explanation, as the pull request is quite different (looks good), I'd like to understand the changes before merging - working on that.
Thanks for the effort, it has become much better structured.

**Comment by erritis** [comment]
Probably it would be worthwhile to issue the validator not in the form of middleware, but in the form of a guard.
And I'm not entirely sure about the correct choice of response error codes.

**Comment by olger** [comment]
I'll have a look, middleware was the mechanism todo the cross cutting concerns but there maybe additions I didn't 'see'.
The module started to get my JWT validation from former actix versions towards 4

**Comment by olger** [comment]
And, I d prefer to not over-engineer it - fairly simple todo with rust. Makes it hard for people to join in. 
I saw some 'Arc' like structures - probably to share and prevent multiple execution and that's the part that I'd like to look at a bit more. Rust is my hobby language and never too late to learn a bit more.

**Comment by olger** [comment]
Hi @erritis,

It's clear, looks good. Can you update the last part of the README... the use of the docker component for integration testing is not required anymore and the reference to the docs points to 0.6.1 ?
Thanks !

**Comment by olger** [comment]
Did these updates, I'll merge it. 
Thanks for your effort.

**Comment by olger** [comment]
Hi @erritis, 
The setup used to work with Extractors - having no Authenticated User extracted means no authentication. This seems not to work with the pull request. So I have to make some changes to enable this. What did you exactly do to prevent running the token validation twice ?

**Pull request merged**
